version: "3.7"

networks:
  web:

services:
  caddy:
    image: caddy:2.6.4-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - EMAIL
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - data:/data
      - config:/config
    networks:
      web:

  uptime-kuma:
    image: louislam/uptime-kuma:1.21.1
    restart: always
    volumes:
      - /home/ubuntu/uptime-kuma:/app/data
    networks:
      web:

configs:
  Caddyfile:
   file: /home/ubuntu/caddy/Caddyfile

volumes:
  data:
  config: