networks:
  web:
    external: true

services:
  caddy:
    image: caddy:2.11.2-alpine@sha256:24d58e24e4231c6667677a39469a3d843a3222eadbf640f22933f24bed0939ec
    restart: always
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - EMAIL
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - data:/data
      - config:/config
    networks:
      web:

configs:
  Caddyfile:
   file: /home/ubuntu/caddy/Caddyfile

volumes:
  data:
  config: