networks:
  web:
    external: true

services:
  caddy:
    image: caddy:2.11.2-alpine@sha256:fce4f15aad23222c0ac78a1220adf63bae7b94355d5ea28eee53910624acedfa
    restart: always
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - EMAIL
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - data:/data
      - config:/config
    networks:
      web:

configs:
  Caddyfile:
   file: /home/ubuntu/caddy/Caddyfile

volumes:
  data:
  config: