networks:
  web:
    external: true

services:
  scribe:
    container_name: scribe
    image: oci.fariszr.com/fariszr/scribe:latest@sha256:45a46530664d86c46d6849c5731968bbec2b944394c91fd7bb786f6779de1918
    restart: always
    environment:
      - APP_DOMAIN=scribe.aosus.link
      - LUCKY_ENV=production
      - PORT=8080
      - SECRET_KEY_BASE
    networks:
      web:
