networks:
  web:
    external: true

services:
  scribe:
    container_name: scribe
    image: oci.fariszr.com/fariszr/scribe:latest@sha256:66307926bbe76eb05b19addf8a1058e7e6e08ab6ba8317e7d9bc501fd9ed7c4a
    restart: always
    environment:
      - APP_DOMAIN=scribe.aosus.link
      - LUCKY_ENV=production
      - PORT=8080
      - SECRET_KEY_BASE
    networks:
      web:
