networks:
  web:
    external: true

services:
  scribe:
    container_name: scribe
    image: oci.fariszr.com/fariszr/scribe:latest@sha256:0430ed50d5f93cd885cced5ae9f968fcb3455626d6a1522a5bc6e25655945561
    restart: always
    environment:
      - APP_DOMAIN=scribe.aosus.link
      - LUCKY_ENV=production
      - PORT=8080
      - SECRET_KEY_BASE
    networks:
      web:
