version: "3.7"

networks:
  web:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.2.1@sha256:7337368a77873f159435de9ef09567f68c31285ed5f951dec36256c4b267ee44
    container_name: uptime-kuma
    restart: always
    volumes:
      - /home/ubuntu/uptime-kuma:/app/data
    networks:
      web: