name: deploy-status

on:
  push:
    paths:
      - '.github/**'
      - 'docker-compose.yml'
      - 'caddy/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Tailscale
        uses: tailscale/github-action@ce41a99162202a647a4b24c30c558a567b926709
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          hostname: Github-actions
          version: 1.36.2

      - name: Start Deployment
        uses: FarisZR/docker-compose-gitops-action@v1
        env:
          WATCHTOWER_NOTIFICATION_URL: ${{ secrets.watchtower_notification_url }}
          EMAIL: ${{ secrets.caddy_email }}
        with:
          remote_docker_host: ${{ secrets.server_address }}
          tailscale_ssh: true # no need for manual private and public keys
          upload_directory: true # upload docker directory
          docker_compose_directory: caddy # directory to upload
          args: -p status up -d